# Generated by Django 5.2.1 on 2025-05-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotholeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('severity', models.PositiveSmallIntegerField(default=3)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('REJECTED', 'Rejected')], default='REPORTED', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='potholes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
